name: FTP Deploy

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 149.100.151.71
          username: u228544066.sagarroy.com
          password: Ff@0191717756207
          local-dir: server/  # The root directory of your GitHub repo
          server-dir: public_html/school/  # Path to your destination on FTP server
          log-level: verbose
          exclude: "lost+found/**" 
